### ISSUE TITLE
Detected board is invalid or unsolvable

### ISSUE THREAD

**Issue by ar1810** [benediktwerner/opus_magnum_sigmars_garden#1]
I tried using the solver but it says: Too many elements. Found 5, expected at most 1.
It detects the board and the elements correctly with the --show-detection argument but still doesn't work

**Comment by benediktwerner** [comment]
Can you post a screenshot of the board with the detected elements?

**Comment by ar1810** [comment]
![imagen_2024-05-13_194558979](https://github.com/benediktwerner/opus_magnum_sigmars_garden/assets/42499535/d48f191f-4c5a-4c0d-8bb7-50f9fc1cb478)
There

**Comment by benediktwerner** [comment]
Hm, those elements don't really seem correct. At first glance, I can see lots of water/fire/earth/wind classified as metals. Are you sure you followed the instructions correctly? Given how consistent it is, this kinda looks like you positioned the mouse next to the metals for the primal elements and the other way around.

**Comment by ar1810** [comment]
I've followed exactly as the instruction says idk what happened, if you want we can get on a discord call to show you the calibration and behavior while trying to solve

**Comment by benediktwerner** [comment]
Have you tried doing the calibration again? Since the element placement seems correct, the empty.png should be fine but try deleting positions.json and redoing the setup. The fact that the elements are so consistently wrong e.g. all earths are iron, all fires are silver, etc. with all the primitive elements being metals really looks odd to me.

Also try increasing the delay between clicks to something like a second and check what it does at the start. It should hover over all the elements at the bottom left to right, which should be salt, then the 4 primitive elements water, fire, wind, earth, and then quicksilver and the metals.

You can compare to how it looks in this video (ignoring that the cursor looks offset): https://www.youtube.com/watch?v=mLaJSjhnD54

**Comment by ar1810** [comment]
Look, it is me the one doing something wrong? https://youtu.be/femlMN23pTs

**Comment by benediktwerner** [comment]
Yes, you're supposed to hover over the first, second, and third element in order. You hovered over the first, fourth, and third. Although I guess not sure if the description calling it water is accurate, looks like the second element might be air?

**Comment by ar1810** [comment]
Ok I see the missunderstanding, you called water the second element wich is air, now that I've done it correctly gives me this error 
![image](https://github.com/benediktwerner/opus_magnum_sigmars_garden/assets/42499535/5876da10-d1d9-4476-9f99-b33e207fd811)

**Comment by benediktwerner** [comment]
Hm, did you try deleting both `empty.png` and `positions.json`? I guess it's not actually possible to just delete `positions.json` because you'll get mismatched sizes.

**Comment by ar1810** [comment]
Yes I've done that

**Comment by benediktwerner** [comment]
I don't really see how you could get mismatched sizes if your `empty.png` was generated after the `positions.json`.
